# Generated by Django 5.1.3 on 2024-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('contactus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('sponsor_consultation', models.TextField(blank=True, null=True)),
                ('cooperation_consultation', models.TextField(blank=True, null=True)),
                ('competition_consultation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consult',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('contactus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='Feedbackform',
            fields=[
                ('contactus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('feedbackinformation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedbackform',
            },
        ),
        migrations.CreateModel(
            name='Volunteerrecruitment',
            fields=[
                ('contactus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('registrationmethod', models.CharField(blank=True, max_length=255, null=True)),
                ('volunteerrole', models.CharField(blank=True, max_length=255, null=True)),
                ('duty', models.TextField(blank=True, null=True)),
                ('workinghours', models.CharField(blank=True, max_length=255, null=True)),
                ('recruitmentrequirements', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'volunteerrecruitment',
            },
        ),
        migrations.DeleteModel(
            name='ConsultationInfo',
        ),
    ]
