# Generated by Django 5.1.3 on 2024-12-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contactus",
            "0002_consult_contactus_feedbackform_volunteerrecruitment_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consult",
            options={"verbose_name": "咨询", "verbose_name_plural": "咨询"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "联系我们", "verbose_name_plural": "联系我们"},
        ),
        migrations.AlterModelOptions(
            name="feedbackform",
            options={"verbose_name": "反馈表单", "verbose_name_plural": "反馈表单"},
        ),
        migrations.AlterModelOptions(
            name="volunteerrecruitment",
            options={"verbose_name": "志愿者招募", "verbose_name_plural": "志愿者招募"},
        ),
    ]
