# Generated by Django 3.2.25 on 2024-12-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_alter_consult_options_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrecruitment',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='volunteerrecruitment',
            name='registrationmethod',
        ),
        migrations.RemoveField(
            model_name='volunteerrecruitment',
            name='volunteerrole',
        ),
        migrations.RemoveField(
            model_name='volunteerrecruitment',
            name='workinghours',
        ),
        migrations.AddField(
            model_name='volunteerrecruitment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
