# Generated by Django 3.2.8 on 2024-12-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role', models.CharField(blank=True, max_length=255, null=True)),
                ('user_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('user_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('user_birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('user_school', models.CharField(blank=True, max_length=255, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_wechat', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
