# Generated by Django 5.1.3 on 2024-12-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "competition_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="比赛编号"
                    ),
                ),
                (
                    "competition_name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="比赛名称"
                    ),
                ),
                (
                    "competition_info",
                    models.TextField(blank=True, null=True, verbose_name="比赛简介"),
                ),
                (
                    "competition_begintime",
                    models.DateField(
                        blank=True, null=True, verbose_name="比赛开始时间"
                    ),
                ),
                (
                    "competition_endtime",
                    models.DateField(
                        blank=True, null=True, verbose_name="比赛结束时间"
                    ),
                ),
                (
                    "competition_teams",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="比赛队伍数"
                    ),
                ),
                (
                    "competition_prize",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="比赛奖金",
                    ),
                ),
                (
                    "competition_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("数据挖掘", "数据挖掘"),
                            ("数据分析", "数据分析"),
                            ("数学建模", "数学建模"),
                            ("金融数学", "金融数学"),
                            ("人工智能", "人工智能"),
                            ("大数据应用", "大数据应用"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="比赛类型",
                    ),
                ),
                (
                    "competition_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("未开始", "未开始"),
                            ("进行中", "进行中"),
                            ("已结束", "已结束"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="比赛状态",
                    ),
                ),
                (
                    "competition_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("泰迪杯挑战赛", "泰迪杯挑战赛"),
                            ("泰迪杯技能赛", "泰迪杯技能赛"),
                            ("湾区金融数模", "湾区金融数模"),
                            ("华中杯", "华中杯"),
                            ("技能兴鲁", "技能兴鲁"),
                            ("大学生科技节", "大学生科技节"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="比赛类别",
                    ),
                ),
                (
                    "competition_brand",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="比赛品牌"
                    ),
                ),
                (
                    "competition_organization",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="比赛组织者"
                    ),
                ),
            ],
            options={
                "verbose_name": "竞赛",
                "verbose_name_plural": "竞赛",
                "db_table": "competition",
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                ("iqui", models.IntegerField(primary_key=True, serialize=False)),
                ("inquiry_time", models.DateTimeField(blank=True, null=True)),
                ("inquiry_result", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览",
                "verbose_name_plural": "浏览",
                "db_table": "inquiry",
            },
        ),
        migrations.CreateModel(
            name="Surf",
            fields=[
                (
                    "surf_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="浏览编号"
                    ),
                ),
                ("surf_time", models.DateTimeField(blank=True, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="surf_competition.competition",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览",
                "verbose_name_plural": "浏览",
                "db_table": "surf",
            },
        ),
    ]
