# Generated by Django 5.1.3 on 2024-12-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('competition_name', models.CharField(blank=True, max_length=20, null=True)),
                ('competition_info', models.TextField(blank=True, null=True)),
                ('competition_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '竞赛',
                'verbose_name_plural': '竞赛',
                'db_table': 'competition',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('iqui', models.IntegerField(primary_key=True, serialize=False)),
                ('inquiry_time', models.DateTimeField(blank=True, null=True)),
                ('inquiry_result', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
            ],
            options={
                'verbose_name': '浏览',
                'verbose_name_plural': '浏览',
                'db_table': 'inquiry',
            },
        ),
        migrations.CreateModel(
            name='Surf',
            fields=[
                ('surf_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='浏览编号')),
                ('surf_time', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='surf_competition.competition')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
            ],
            options={
                'verbose_name': '浏览',
                'verbose_name_plural': '浏览',
                'db_table': 'surf',
            },
        ),
    ]
