# Generated by Django 5.1.3 on 2024-11-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('competition_name', models.CharField(blank=True, max_length=20, null=True)),
                ('competition_info', models.TextField(blank=True, null=True)),
                ('competition_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('iqui', models.IntegerField(primary_key=True, serialize=False)),
                ('inquiry_time', models.DateTimeField(blank=True, null=True)),
                ('inquiry_result', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surf',
            fields=[
                ('surf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surf_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'surf',
                'managed': False,
            },
        ),
    ]
