# Generated by Django 5.1.3 on 2024-12-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf_competition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='competition_time',
            new_name='competition_begintime',
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_endtime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_prize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='比赛奖金'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_status',
            field=models.CharField(blank=True, choices=[('not_started', '未开始'), ('ongoing', '进行中'), ('finished', '已结束')], max_length=40, null=True, verbose_name='比赛状态'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(blank=True, choices=[('data_mining', '数据挖掘'), ('data_analysis', '数据分析'), ('math_modeling', '数学建模'), ('financial_math', '金融数学'), ('artificial_intelligence', '人工智能'), ('big_data', '大数据应用')], max_length=40, null=True, verbose_name='比赛类型'),
        ),
    ]
